=== AlphSpirit/flesh-and-blood-cards/json-schema/keyword-schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "array",
    "items": {
        "type": "object",
        "properties": {
            "unique_id": {
                "type": "string"
            },
            "keyword": {
                "type": "string"
            },
            "description": {
                "type": "string"
            },
            "description_plain": {
                "type": "string"
            }
        },
        "required": [
            "unique_id",
            "keyword",
            "description",
            "description_plain"
        ]
    }
}

=== AlphSpirit/flesh-and-blood-cards/json/french/keyword.json
[
    {
        "unique_id": "77JKJwz6k8BRrGbmRDPTT",
        "keyword": "Blocage Arcane X",
        "description": "",
        "description_plain": ""
    },
    {
        "unique_id": "tHNMT9DMtgRNTBrnCjdWq",
        "keyword": "Attaque",
        "description": "",
        "description_plain": ""
    },
    {
        "unique_id": "bKgtwKPTzJ69QdFDfm9bR",
        "keyword": "Usure de Guerre",
        "description": "",
        "description_plain": ""
    },
    {
        "unique_id": "cG88qzrJhwLnJH6TJ9cpp",
        "keyword": "Lame Brisée",
        "description": "",
        "description_plain": ""
    },
    {
        "unique_id": "wPWTbtBBwWkLhTz7hMrn7",
        "keyword": "Boostez",
        "description": "",
        "description_plain": ""
    },
    {
        "unique_id": "H6nNm6Nndrp8qTGFJL7GB",
        "keyword": "Combo",
        "description": "",
        "description_plain": ""
    },
    {
        "unique_id": "rG7F9GkDcmwNMczRbtwhL",
        "keyword": "Écrasement",
        "description": "",
        "description_plain": ""
    },
    {
        "unique_id": "LdpzkhTrrcHJJtLFnctGW",
        "keyword": "Dominer",
        "description": "",
        "description_plain": ""
    },
    {
        "unique_id": "mmf6BdTtrbCGrhdhg8K9g",
        "keyword": "Go again",
        "description": "",
        "description_plain": ""
    },
    {
        "unique_id": "NdTgddPBhJLhG7HRjqPG6",
        "keyword": "Intimidez",
        "description": "",
        "description_plain": ""
    },
    {
        "unique_id": "TrD8trBHtDqmdKtd9jMWr",
        "keyword": "Légendaire",
        "description": "",
        "description_plain": ""
    },
    {
        "unique_id": "bfRPRwTzzCPNRmNbfhdq7",
        "keyword": "Optez X",
        "description": "",
        "description_plain": ""
    },
    {
        "unique_id": "CMkCBFwkdRTkckLfBwhjL",
        "keyword": "Rechargez",
        "description": "",
        "description_plain": ""
    },
    {
        "unique_id": "BN9pfqWtQjNgCHFrgmNHJ",
        "keyword": "Reprise",
        "description": "",
        "description_plain": ""
    },
    {
        "unique_id": "cjn8CBRWPmdG8fwJNTBJt",
        "keyword": "Spécialisation",
        "description": "",
        "description_plain": ""
    },
    {
        "unique_id": "RnrzPrG6KfnCPhDCF8bpB",
        "keyword": "Temper",
        "description": "",
        "description_plain": ""
    }
]

=== AlphSpirit/flesh-and-blood-cards/json/spanish/keyword.json
[
    {
        "unique_id": "77JKJwz6k8BRrGbmRDPTT",
        "keyword": "Barrera arcana 2",
        "description": "",
        "description_plain": ""
    },
    {
        "unique_id": "tHNMT9DMtgRNTBrnCjdWq",
        "keyword": "Atacar",
        "description": "",
        "description_plain": ""
    },
    {
        "unique_id": "bKgtwKPTzJ69QdFDfm9bR",
        "keyword": "Desgaste de batalla",
        "description": "",
        "description_plain": ""
    },
    {
        "unique_id": "cG88qzrJhwLnJH6TJ9cpp",
        "keyword": "Rotura de espada",
        "description": "",
        "description_plain": ""
    },
    {
        "unique_id": "wPWTbtBBwWkLhTz7hMrn7",
        "keyword": "Potenciar",
        "description": "",
        "description_plain": ""
    },
    {
        "unique_id": "H6nNm6Nndrp8qTGFJL7GB",
        "keyword": "Combo",
        "description": "",
        "description_plain": ""
    },
    {
        "unique_id": "rG7F9GkDcmwNMczRbtwhL",
        "keyword": "Aplastar",
        "description": "",
        "description_plain": ""
    },
    {
        "unique_id": "LdpzkhTrrcHJJtLFnctGW",
        "keyword": "Dominar",
        "description": "",
        "description_plain": ""
    },
    {
        "unique_id": "mmf6BdTtrbCGrhdhg8K9g",
        "keyword": "Continuar",
        "description": "",
        "description_plain": ""
    },
    {
        "unique_id": "NdTgddPBhJLhG7HRjqPG6",
        "keyword": "Intimidar",
        "description": "",
        "description_plain": ""
    },
    {
        "unique_id": "TrD8trBHtDqmdKtd9jMWr",
        "keyword": "Legendario",
        "description": "",
        "description_plain": ""
    },
    {
        "unique_id": "bfRPRwTzzCPNRmNbfhdq7",
        "keyword": "Opta X",
        "description": "",
        "description_plain": ""
    },
    {
        "unique_id": "CMkCBFwkdRTkckLfBwhjL",
        "keyword": "Recargar",
        "description": "",
        "description_plain": ""
    },
    {
        "unique_id": "BN9pfqWtQjNgCHFrgmNHJ",
        "keyword": "Vuelta",
        "description": "",
        "description_plain": ""
    },
    {
        "unique_id": "cjn8CBRWPmdG8fwJNTBJt",
        "keyword": "Especialización",
        "description": "",
        "description_plain": ""
    },
    {
        "unique_id": "RnrzPrG6KfnCPhDCF8bpB",
        "keyword": "Carácter",
        "description": "",
        "description_plain": ""
    }
]

=== AlphSpirit/flesh-and-blood-cards/json/italian/keyword.json
[
    {
        "unique_id": "77JKJwz6k8BRrGbmRDPTT",
        "keyword": "Barriera Arcana X",
        "description": "",
        "description_plain": ""
    },
    {
        "unique_id": "tHNMT9DMtgRNTBrnCjdWq",
        "keyword": "Attacco",
        "description": "",
        "description_plain": ""
    },
    {
        "unique_id": "bKgtwKPTzJ69QdFDfm9bR",
        "keyword": "Consumato in battaglia",
        "description": "",
        "description_plain": ""
    },
    {
        "unique_id": "cG88qzrJhwLnJH6TJ9cpp",
        "keyword": "Lâ€™arma si spezza",
        "description": "",
        "description_plain": ""
    },
    {
        "unique_id": "wPWTbtBBwWkLhTz7hMrn7",
        "keyword": "Potenzia",
        "description": "",
        "description_plain": ""
    },
    {
        "unique_id": "H6nNm6Nndrp8qTGFJL7GB",
        "keyword": "Combo",
        "description": "",
        "description_plain": ""
    },
    {
        "unique_id": "rG7F9GkDcmwNMczRbtwhL",
        "keyword": "Schianta",
        "description": "",
        "description_plain": ""
    },
    {
        "unique_id": "LdpzkhTrrcHJJtLFnctGW",
        "keyword": "Domina",
        "description": "",
        "description_plain": ""
    },
    {
        "unique_id": "mmf6BdTtrbCGrhdhg8K9g",
        "keyword": "Continua",
        "description": "",
        "description_plain": ""
    },
    {
        "unique_id": "NdTgddPBhJLhG7HRjqPG6",
        "keyword": "Intimidisci",
        "description": "",
        "description_plain": ""
    },
    {
        "unique_id": "TrD8trBHtDqmdKtd9jMWr",
        "keyword": "Leggendaria",
        "description": "",
        "description_plain": ""
    },
    {
        "unique_id": "bfRPRwTzzCPNRmNbfhdq7",
        "keyword": "Opta X",
        "description": "",
        "description_plain": ""
    },
    {
        "unique_id": "CMkCBFwkdRTkckLfBwhjL",
        "keyword": "Rechargez",
        "description": "",
        "description_plain": ""
    },
    {
        "unique_id": "BN9pfqWtQjNgCHFrgmNHJ",
        "keyword": "Ricarica",
        "description": "",
        "description_plain": ""
    },
    {
        "unique_id": "cjn8CBRWPmdG8fwJNTBJt",
        "keyword": "Specializzazione",
        "description": "",
        "description_plain": ""
    },
    {
        "unique_id": "RnrzPrG6KfnCPhDCF8bpB",
        "keyword": "Tempra",
        "description": "",
        "description_plain": ""
    }
]

=== AlphSpirit/flesh-and-blood-cards/json/german/keyword.json
[
    {
        "unique_id": "77JKJwz6k8BRrGbmRDPTT",
        "keyword": "Arkane Barriere X",
        "description": "",
        "description_plain": ""
    },
    {
        "unique_id": "tHNMT9DMtgRNTBrnCjdWq",
        "keyword": "Attacke",
        "description": "",
        "description_plain": ""
    },
    {
        "unique_id": "bKgtwKPTzJ69QdFDfm9bR",
        "keyword": "Von der Schlacht gezeichnet",
        "description": "",
        "description_plain": ""
    },
    {
        "unique_id": "cG88qzrJhwLnJH6TJ9cpp",
        "keyword": "Klingenbruch",
        "description": "",
        "description_plain": ""
    },
    {
        "unique_id": "wPWTbtBBwWkLhTz7hMrn7",
        "keyword": "Boost",
        "description": "",
        "description_plain": ""
    },
    {
        "unique_id": "H6nNm6Nndrp8qTGFJL7GB",
        "keyword": "Kombo",
        "description": "",
        "description_plain": ""
    },
    {
        "unique_id": "rG7F9GkDcmwNMczRbtwhL",
        "keyword": "Zerschmetterung",
        "description": "",
        "description_plain": ""
    },
    {
        "unique_id": "LdpzkhTrrcHJJtLFnctGW",
        "keyword": "Dominieren",
        "description": "",
        "description_plain": ""
    },
    {
        "unique_id": "mmf6BdTtrbCGrhdhg8K9g",
        "keyword": "Go again",
        "description": "",
        "description_plain": ""
    },
    {
        "unique_id": "NdTgddPBhJLhG7HRjqPG6",
        "keyword": "Einschüchtern",
        "description": "",
        "description_plain": ""
    },
    {
        "unique_id": "TrD8trBHtDqmdKtd9jMWr",
        "keyword": "Legendär",
        "description": "",
        "description_plain": ""
    },
    {
        "unique_id": "bfRPRwTzzCPNRmNbfhdq7",
        "keyword": "Sortiere X Um",
        "description": "",
        "description_plain": ""
    },
    {
        "unique_id": "CMkCBFwkdRTkckLfBwhjL",
        "keyword": "Nachladen",
        "description": "",
        "description_plain": ""
    },
    {
        "unique_id": "BN9pfqWtQjNgCHFrgmNHJ",
        "keyword": "Fortführen",
        "description": "",
        "description_plain": ""
    },
    {
        "unique_id": "cjn8CBRWPmdG8fwJNTBJt",
        "keyword": "Spezialisierung",
        "description": "",
        "description_plain": ""
    },
    {
        "unique_id": "RnrzPrG6KfnCPhDCF8bpB",
        "keyword": "Tempern",
        "description": "",
        "description_plain": ""
    }
]
